#!/bin/sh
# Run by github/github codespaces after starting

# Install packages.
apt-get install -y \
  zsh-autosuggestions \
  colordiff

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  chsh -s /bin/zsh root
fi
