#!/bin/sh
# Run by github/github codespaces after starting

for user in {root,vscode}; do
  # Always want to use ZSH as my default shell (e.g. for SSH)
  if ! grep -q "root.*/bin/zsh" /etc/passwd
  then
    sudo chsh -s /bin/zsh "$user"
  fi
done
